### ISSUE TITLE
Magic Siphon granting infinite duration potion effects from Apotheosis mobs

### ISSUE THREAD

**Issue by incomingnerd** [Darkhax-Minecraft/Corail-Tombstone#25]
**Problem**
Apotheosis Swarm Spawners (plus other mods, most likely) generate buffed mobs with infinite duration potion effects. The Magic Siphon enchantment transfers these effects as-is, resulting in players gaining permanent buffs for very little effort.

**Suggestion**
Cap the duration of transferred potion effects from Magic Siphon to some (configurable) limit.

**Versions**
Minecraft 1.15.2
Apotheosis 1.15.2-3.3.8
Corail Tombstone 4.5.6

**Comment by incomingnerd** [comment]
For reference: https://github.com/Shadows-of-Fire/Apotheosis/issues/259#issue-752753028

**Comment by Corail31** [comment]
The config already exists
https://github.com/Darkhax-Minecraft/Corail-Tombstone/blob/corail-1.15.2/src/main/java/ovh/corail/tombstone/config/ConfigTombstone.java#L134

**Comment by incomingnerd** [comment]
My bad. I missed that option. Thanks for answering!
