### ISSUE TITLE
[1.16.1] Crash on mouse click on World loading

### ISSUE THREAD

**Issue by 3x1at1on** [Darkhax-Minecraft/Corail-Tombstone#5]
Crash happens with mouse click on world to load.

Crash log https://pastebin.com/JitfQZaf

More detailed log https://pastebin.com/ByAeSUx3

**Comment by Brandon-Wolff** [comment]
I'm having the same crash. 
https://pastebin.com/nyN5aRwu

**Comment by Darkhax** [comment]
Thank you for reporting. I've released a new beta `5.0.2` which should fix this issue. If it's not on CurseForge give them a bit to update the files.
