### ISSUE TITLE
Crash server 1.16.1

### ISSUE THREAD

**Issue by osdeibi** [Darkhax-Minecraft/Corail-Tombstone#6]
Crash on server start 1.16.1 forge version "1.16.1 - 32.0.108"
log file: https://pastebin.com/aLH5nwTJ

**Comment by hron84** [comment]
Same with singleplayer world generaton.

**Comment by Darkhax** [comment]
Thank you for reporting. I've released a new beta `5.0.2` which should fix this issue. If it's not on CurseForge give them a bit to update the files.

**Comment by osdeibi** [comment]
Thanks. Fixed now with version 5.0.2
